from __future__ import annotations


FINANCE_INCOME_VIP_FIELDS: tuple[str, ...] = (
    "total_revenue",
    "revenue",
    "operate_profit",
    "total_profit",
    "n_income_attr_p",
    "basic_eps",
    "diluted_eps",
)

FINANCE_BALANCESHEET_VIP_FIELDS: tuple[str, ...] = (
    "total_assets",
    "total_liab",
    "total_hldr_eqy_exc_min_int",
)

FINANCE_CASHFLOW_VIP_FIELDS: tuple[str, ...] = (
    "n_cashflow_act",
    "n_cashflow_inv_act",
    "n_cash_flows_fnc_act",
)

FINA_INDICATOR_VIP_FIELDS: tuple[str, ...] = (
    "current_ratio",
    "quick_ratio",
    "cash_ratio",
    "inv_turn",
    "ar_turn",
    "ca_turn",
    "fa_turn",
    "assets_turn",
    "ocfps",
    "retainedps",
    "cfps",
    "fcff_ps",
    "fcfe_ps",
    "cogs_of_sales",
    "expense_of_sales",
    "profit_to_gr",
    "saleexp_to_gr",
    "adminexp_of_gr",
    "finaexp_of_gr",
    "impai_ttm",
    "gc_of_gr",
    "op_of_gr",
    "ebit_of_gr",
    "grossprofit_margin",
    "netprofit_margin",
    "roe",
    "roe_waa",
    "roe_dt",
    "roa",
    "npta",
    "roic",
    "roe_avg",
    "opincome_of_ebt",
    "investincome_of_ebt",
    "n_op_profit_of_ebt",
    "tax_to_ebt",
    "dtprofit_to_profit",
    "salescash_to_or",
    "ocf_to_or",
    "ocf_to_opincome",
    "capitalized_to_da",
    "debt_to_assets",
    "assets_to_eqt",
    "dp_assets_to_eqt",
    "ca_to_assets",
    "nca_to_assets",
    "tbassets_to_totalassets",
    "int_to_talcap",
    "eqt_to_talcapital",
    "currentdebt_to_debt",
    "longdeb_to_debt",
    "ocf_to_shortdebt",
    "debt_to_eqt",
    "eqt_to_debt",
    "eqt_to_interestdebt",
    "tangibleasset_to_debt",
    "tangasset_to_intdebt",
    "tangibleasset_to_netdebt",
    "ocf_to_debt",
    "ocf_to_interestdebt",
    "ocf_to_netdebt",
    "ebit_to_interest",
    "longdebt_to_workingcapital",
    "ebitda_to_debt",
    "op_to_ebt",
    "nop_to_ebt",
    "ocf_to_profit",
    "cash_to_liqdebt",
    "cash_to_liqdebt_withinterest",
    "op_to_liqdebt",
    "op_to_debt",
    "roic_yearly",
    "total_fa_trun",
    "profit_to_op",
    "q_profit_to_gr",
    "q_saleexp_to_gr",
    "q_adminexp_to_gr",
    "q_finaexp_to_gr",
    "q_impair_to_gr_ttm",
    "q_gc_to_gr",
    "q_op_to_gr",
    "q_roe",
    "q_dt_roe",
    "q_npta",
    "q_opincome_to_ebt",
    "q_investincome_to_ebt",
    "q_dtprofit_to_profit",
    "q_salescash_to_or",
    "q_ocf_to_sales",
    "q_ocf_to_or",
    "cfps_yoy",
    "op_yoy",
    "ebt_yoy",
    "ocf_yoy",
)

FINANCE_ASOF_FIELD_MAP: dict[str, tuple[str, str]] = {
    "fin_income_ann_date": ("income", "ann_date"),
    "fin_income_end_date": ("income", "end_date"),
    **{f"fin_{field}": ("income", field) for field in FINANCE_INCOME_VIP_FIELDS},
    "fin_balance_ann_date": ("balance", "ann_date"),
    "fin_balance_end_date": ("balance", "end_date"),
    **{f"fin_{field}": ("balance", field) for field in FINANCE_BALANCESHEET_VIP_FIELDS},
    "fin_cashflow_ann_date": ("cashflow", "ann_date"),
    "fin_cashflow_end_date": ("cashflow", "end_date"),
    **{f"fin_{field}": ("cashflow", field) for field in FINANCE_CASHFLOW_VIP_FIELDS},
    "fin_indicator_ann_date": ("indicator", "ann_date"),
    "fin_indicator_end_date": ("indicator", "end_date"),
    **{f"fin_{field}": ("indicator", field) for field in FINA_INDICATOR_VIP_FIELDS},
}

FINANCE_ASOF_PANEL_FIELDS: tuple[str, ...] = tuple(FINANCE_ASOF_FIELD_MAP)


def finance_vip_field_request(fields: tuple[str, ...]) -> str:
    return "ts_code,ann_date,end_date," + ",".join(fields)
