from __future__ import annotations

from typing import Any


SAFE_SOURCE_CHUNK_HARD_LIMIT_MB = 4096


def closed_loop_param_schema() -> dict[str, Any]:
    groups = [
        {
            "id": "basic",
            "label": "Basic",
            "params": [
                _param("universe", "Universe", "string", "cn_all", required=True),
                _param("start_date", "Start date", "date", "2022-01-01"),
                _param(
                    "end_date",
                    "End date",
                    "date",
                    "",
                    placeholder="empty = latest available",
                ),
                _param("request_new", "Request new", "number", 5, min=1, max=200),
                _param("batch_size", "Batch size", "number", 5, min=1, max=100),
                _param(
                    "max_eval",
                    "Max evaluations",
                    "number",
                    80,
                    min=1,
                    max=5000,
                    risk="medium",
                ),
                _param(
                    "iterations",
                    "Iterations",
                    "number",
                    1,
                    min=1,
                    max=20,
                    risk="medium",
                ),
                _param(
                    "search_mode",
                    "Search mode",
                    "select",
                    "layered_v2",
                    options=[
                        "layered_v2",
                        "template_only",
                        "deep_hybrid",
                        "operator_only",
                    ],
                ),
            ],
        },
        {
            "id": "data",
            "label": "Data Source",
            "params": [
                _param(
                    "source_backend",
                    "Source backend",
                    "select",
                    "duckdb",
                    options=["duckdb", "file"],
                ),
                _param(
                    "datasource_config",
                    "Datasource config",
                    "string",
                    "configs/datasource.local.yaml",
                ),
                _param("duckdb_path", "DuckDB path", "string", "data/duckdb/market.duckdb"),
                _param("source_view", "Source view", "string", "v_project_panel_cn_a"),
                _param("data_path", "File backend path", "string", ""),
                _param(
                    "run_filters_json",
                    "Run filters JSON",
                    "json",
                    "",
                    placeholder="JSON object",
                ),
                _param("include_fields", "Include fields", "string", ""),
                _param("exclude_fields", "Exclude fields", "string", ""),
                _param("include_factor_families", "Include families", "string", ""),
                _param("exclude_factor_families", "Exclude families", "string", ""),
            ],
        },
        {
            "id": "generation",
            "label": "Generation",
            "params": [
                _param("layer_max_order", "Layer max order", "number", 4, min=0, max=4),
                _param(
                    "layer_max_candidates",
                    "Layer max candidates",
                    "number",
                    0,
                    min=0,
                    max=20000,
                    risk="medium",
                ),
                _param(
                    "layer_budget_json",
                    "Layer budget JSON",
                    "json",
                    "",
                    placeholder='e.g. {"L0":32,"L1":160}',
                ),
                _param("sample_prefilter", "Sample prefilter", "boolean", False),
                _param(
                    "sample_max_evaluations",
                    "Sample max evaluations",
                    "number",
                    60,
                    min=1,
                    max=1000,
                ),
                _param("enable_feedback_mutation", "Feedback mutation", "boolean", False),
                _param(
                    "score_weights_json",
                    "Score weights JSON",
                    "json",
                    "",
                    placeholder='e.g. {"feedback":0.20,"novelty":0.18}',
                ),
                _param(
                    "complexity_weight",
                    "Complexity weight",
                    "number",
                    0.10,
                    min=0,
                    max=1,
                ),
                _param(
                    "mutation_budget_ratio",
                    "Mutation budget ratio",
                    "number",
                    0.15,
                    min=0,
                    max=1,
                ),
                _param(
                    "feedback_min_explore_ratio",
                    "Feedback explore ratio",
                    "number",
                    0.30,
                    min=0,
                    max=1,
                ),
                _param(
                    "feedback_exploit_ratio",
                    "Feedback exploit ratio",
                    "number",
                    0.55,
                    min=0,
                    max=1,
                ),
                _param(
                    "feedback_lookback_batches",
                    "Feedback lookback batches",
                    "number",
                    50,
                    min=1,
                    max=500,
                ),
                _param("layer_windows", "Layer windows", "string", "5,10,22,66,132"),
            ],
        },
        {
            "id": "analysis",
            "label": "Analysis",
            "params": [
                _param("analysis_period", "Analysis period", "number", 1, min=1, max=60),
                _param("analysis_layers", "Analysis layers", "number", 10, min=2, max=50),
                _param(
                    "effectiveness_ic_min",
                    "Effectiveness IC min",
                    "number",
                    0.015,
                    min=0,
                    max=1,
                ),
                _param(
                    "effectiveness_ir_min",
                    "Effectiveness IR min",
                    "number",
                    0.25,
                    min=0,
                    max=5,
                ),
                _param(
                    "effectiveness_sharpe_min",
                    "Effectiveness Sharpe min",
                    "number",
                    0.40,
                    min=0,
                    max=10,
                ),
                _param(
                    "effectiveness_coverage_min",
                    "Effectiveness coverage min",
                    "number",
                    0.60,
                    min=0,
                    max=1,
                ),
                _param(
                    "effectiveness_turnover_max",
                    "Effectiveness turnover max",
                    "number",
                    0.80,
                    min=0,
                    max=1,
                ),
                _param(
                    "effectiveness_min_score",
                    "Effectiveness min score",
                    "number",
                    50,
                    min=0,
                    max=100,
                ),
                _param("long10_count", "Long top N count", "number", 10, min=1, max=100),
                _param(
                    "neutralization",
                    "Neutralization",
                    "select",
                    "NONE",
                    options=["NONE", "MARKET", "SECTOR", "INDUSTRY", "SUBINDUSTRY"],
                ),
                _param("include_double_sort", "Double sort", "boolean", False),
                _param("train_start", "Train start", "date", "2016-01-01"),
                _param("train_end", "Train end", "date", "2024-12-31"),
                _param("validation_start", "Validation start", "date", "2025-01-01"),
                _param("validation_end", "Validation end", "date", "2025-12-31"),
                _param("oos_start", "OOS start", "date", "2026-01-01"),
                _param(
                    "include_sample_split_analysis",
                    "Sample split analysis",
                    "boolean",
                    False,
                ),
                _param("benchmark_enabled", "Benchmark enabled", "boolean", True),
                _param("benchmark_code", "Benchmark code", "string", ""),
                _param("transaction_cost_enabled", "Transaction cost", "boolean", True),
                _param(
                    "include_visualization_png",
                    "Visualization PNG",
                    "boolean",
                    False,
                    risk="medium",
                ),
            ],
        },
        {
            "id": "resources",
            "label": "Resources",
            "params": [
                _param("source_chunk_loading", "Source chunk loading", "boolean", True),
                _param(
                    "source_chunk_mem_warn_mb",
                    "Chunk memory warning MB",
                    "number",
                    2560,
                    min=128,
                    max=65536,
                ),
                _param(
                    "source_chunk_mem_hard_limit_mb",
                    "Chunk memory hard limit MB",
                    "number",
                    SAFE_SOURCE_CHUNK_HARD_LIMIT_MB,
                    min=512,
                    max=131072,
                ),
                _param("duckdb_memory_limit", "DuckDB memory limit", "string", ""),
                _param("duckdb_threads", "DuckDB threads", "number", 0, min=0, max=64),
                _param("duckdb_temp_directory", "DuckDB temp dir", "string", ""),
                _param(
                    "duckdb_max_temp_directory_size",
                    "DuckDB max temp size",
                    "string",
                    "",
                ),
                _param(
                    "candidate_artifact_retention_enabled",
                    "Candidate retention",
                    "boolean",
                    True,
                ),
                _param(
                    "analysis_artifact_retention_enabled",
                    "Analysis retention",
                    "boolean",
                    False,
                ),
                _param(
                    "run_health_retention_enabled",
                    "Run-health retention",
                    "boolean",
                    True,
                ),
            ],
        },
        {
            "id": "library",
            "label": "Library",
            "params": [
                _param("factor_library", "Submit to library", "boolean", False),
                _param(
                    "factor_library_min_score",
                    "Accepted min score",
                    "number",
                    60,
                    min=0,
                    max=100,
                ),
                _param(
                    "factor_library_staging_min_score",
                    "Staging min score",
                    "number",
                    50,
                    min=0,
                    max=100,
                ),
                _param(
                    "factor_library_max_signal_corr",
                    "Max signal corr",
                    "number",
                    0.80,
                    min=0,
                    max=1,
                ),
                _param(
                    "factor_library_max_ic_corr",
                    "Max IC corr",
                    "number",
                    0.80,
                    min=0,
                    max=1,
                ),
                _param(
                    "factor_library_max_pnl_corr",
                    "Max PnL corr",
                    "number",
                    0.80,
                    min=0,
                    max=1,
                ),
                _param(
                    "factor_library_staging_max_corr",
                    "Staging max corr",
                    "number",
                    0.95,
                    min=0,
                    max=1,
                ),
            ],
        },
    ]
    presets = [
        {
            "id": "smoke",
            "label": "Smoke",
            "description": "Small local smoke run for checking data and wiring.",
            "risk": "low",
            "params": {
                "request_new": 5,
                "batch_size": 5,
                "max_eval": 80,
                "iterations": 1,
            },
        },
        {
            "id": "balanced",
            "label": "Balanced",
            "description": "Moderate research run for routine local exploration.",
            "risk": "medium",
            "params": {
                "request_new": 20,
                "batch_size": 10,
                "max_eval": 500,
                "iterations": 2,
            },
        },
        {
            "id": "deep",
            "label": "Deep",
            "description": "Longer mining run with higher local resource usage.",
            "risk": "high",
            "params": {
                "request_new": 50,
                "batch_size": 10,
                "max_eval": 2000,
                "iterations": 3,
            },
        },
    ]
    return {
        "status": "ok",
        "groups": groups,
        "presets": presets,
        "safe_defaults": {"source_chunk_mem_hard_limit_mb": SAFE_SOURCE_CHUNK_HARD_LIMIT_MB},
    }


def _param(
    name: str,
    label: str,
    kind: str,
    default: Any,
    *,
    required: bool = False,
    options: list[str] | None = None,
    min: float | None = None,
    max: float | None = None,
    risk: str = "low",
    placeholder: str | None = None,
) -> dict[str, Any]:
    out = {
        "name": name,
        "label": label,
        "type": kind,
        "default": default,
        "required": bool(required),
        "risk": risk,
    }
    if options is not None:
        out["options"] = options
    if min is not None:
        out["min"] = min
    if max is not None:
        out["max"] = max
    if placeholder is not None:
        out["placeholder"] = placeholder
    return out
